package com.velocitychat;

import org.slf4j.Logger;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Manages player title groups.
 * <p>
 * Each group has a name and a title (prefix) displayed before the player's name
 * when they send a broadcast message. Group members are stored in a groups.yml
 * file in the plugin's data directory.
 */
public class GroupManager {

    private final Logger logger;
    private final Path dataDirectory;

    // group name -> group data
    private final Map<String, Group> groups = new ConcurrentHashMap<>();

    // player name (lowercase) -> group name
    private final Map<String, String> playerGroups = new ConcurrentHashMap<>();

    public GroupManager(Logger logger, Path dataDirectory) {
        this.logger = logger;
        this.dataDirectory = dataDirectory;
    }

    /**
     * Load groups from the groups.yml data file.
     */
    @SuppressWarnings("unchecked")
    public void load() {
        groups.clear();
        playerGroups.clear();

        Path groupsFile = dataDirectory.resolve("groups.yml");
        if (!Files.exists(groupsFile)) {
            logger.info("No groups.yml found, starting with empty groups");
            return;
        }

        try (InputStream in = Files.newInputStream(groupsFile)) {
            Yaml yaml = new Yaml();
            Object loaded = yaml.load(in);
            if (!(loaded instanceof Map<?, ?> root)) return;

            Object groupsData = root.get("groups");
            if (!(groupsData instanceof List<?> groupList)) return;

            for (Object obj : groupList) {
                if (!(obj instanceof Map<?, ?> entry)) continue;

                String name = getStr(entry, "name");
                String title = getStr(entry, "title");

                if (name == null) continue;
                if (title == null) title = "";

                List<String> members = new ArrayList<>();
                if (entry.get("members") instanceof List<?> memberList) {
                    for (Object m : memberList) {
                        if (m != null) members.add(m.toString());
                    }
                }

                Group group = new Group(name, title, members);
                groups.put(name.toLowerCase(), group);
                for (String member : members) {
                    playerGroups.put(member.toLowerCase(), name.toLowerCase());
                }
            }

            logger.info("Loaded {} groups from groups.yml", groups.size());
        } catch (Exception e) {
            logger.warn("Failed to load groups.yml", e);
        }
    }

    /**
     * Save groups to the groups.yml data file.
     */
    public void save() {
        Path groupsFile = dataDirectory.resolve("groups.yml");

        // Build the YAML structure manually
        StringBuilder sb = new StringBuilder();
        sb.append("# VelocityChat Groups Data\n");
        sb.append("# 请勿手动编辑此文件 / Do not edit this file manually\n");
        sb.append("groups:\n");

        for (Group group : groups.values()) {
            sb.append("  - name: \"").append(escapeYaml(group.name)).append("\"\n");
            sb.append("    title: \"").append(escapeYaml(group.title)).append("\"\n");
            sb.append("    members:\n");
            for (String member : group.members) {
                sb.append("      - \"").append(escapeYaml(member)).append("\"\n");
            }
        }

        try {
            Files.createDirectories(dataDirectory);
            Files.writeString(groupsFile, sb.toString());
        } catch (IOException e) {
            logger.warn("Failed to save groups.yml", e);
        }
    }

    // ── Group Management API ─────────────────────────────────

    /**
     * Create a new group with the given name and title.
     *
     * @return true if the group was created, false if it already exists
     */
    public boolean createGroup(String name, String title) {
        String key = name.toLowerCase();
        if (groups.containsKey(key)) {
            return false;
        }
        groups.put(key, new Group(name, title, new ArrayList<>()));
        save();
        logger.info("Created group '{}' with title '{}'", name, title);
        return true;
    }

    /**
     * Delete a group. Removes all member associations.
     *
     * @return true if the group was deleted, false if it didn't exist
     */
    public boolean deleteGroup(String name) {
        String key = name.toLowerCase();
        Group removed = groups.remove(key);
        if (removed == null) return false;

        // Clean up player mappings (playerGroups 键是小写)
        for (String member : removed.members) {
            playerGroups.remove(member.toLowerCase());
        }
        save();
        logger.info("Deleted group '{}'", name);
        return true;
    }

    /**
     * Add a player to a group.
     *
     * @return true if successful, false if group doesn't exist or player is already in a group
     */
    public boolean addMember(String groupName, String playerName) {
        String groupKey = groupName.toLowerCase();
        String playerKey = playerName.toLowerCase();

        Group group = groups.get(groupKey);
        if (group == null) return false;

        // Remove from any existing group first
        removeMember(playerName);

        group.members.add(playerName); // 保留原始大小写
        playerGroups.put(playerKey, groupKey);
        save();
        logger.info("Added player '{}' to group '{}'", playerName, groupName);
        return true;
    }

    /**
     * Remove a player from their current group.
     *
     * @return true if the player was in a group and was removed
     */
    public boolean removeMember(String playerName) {
        String playerKey = playerName.toLowerCase();
        String groupKey = playerGroups.remove(playerKey);
        if (groupKey == null) return false;

        Group group = groups.get(groupKey);
        if (group != null) {
            // Find and remove member ignoring case (保留原始大小写显示)
            group.members.removeIf(m -> m.equalsIgnoreCase(playerName));
            save();
            logger.info("Removed player '{}' from group '{}'", playerName, group.name);
        }
        return true;
    }

    /**
     * Get the display title for a player, or empty string if they have no group.
     * The title already includes color codes.
     */
    public String getPlayerTitle(String playerName) {
        if (playerName == null) return "";
        String playerKey = playerName.toLowerCase();
        String groupKey = playerGroups.get(playerKey);
        if (groupKey == null) return "";

        Group group = groups.get(groupKey);
        if (group == null) return "";

        return ColorUtils.translate(group.title);
    }

    /**
     * Get the group name a player belongs to, or null if none.
     */
    public String getPlayerGroup(String playerName) {
        if (playerName == null) return null;
        String playerKey = playerName.toLowerCase();
        String groupKey = playerGroups.get(playerKey);
        if (groupKey == null) return null;

        Group group = groups.get(groupKey);
        return group != null ? group.name : null;
    }

    /**
     * Get all groups.
     */
    public Map<String, Group> getGroups() {
        return Collections.unmodifiableMap(groups);
    }

    /**
     * Get group by name.
     */
    public Group getGroup(String name) {
        return groups.get(name.toLowerCase());
    }

    /**
     * Check if a group exists.
     */
    public boolean groupExists(String name) {
        return groups.containsKey(name.toLowerCase());
    }

    // ── Internal ─────────────────────────────────────────────

    private static String getStr(Map<?, ?> map, String key) {
        Object v = map.get(key);
        return v != null ? v.toString() : null;
    }

    private static String escapeYaml(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    // ── Group Data Class ──────────────────────────────────────

    public static class Group {
        private final String name;
        private String title;
        private final List<String> members;

        public Group(String name, String title, List<String> members) {
            this.name = name;
            this.title = title;
            this.members = new ArrayList<>(members);
        }

        public String getName() { return name; }
        public String getTitle() { return title; }
        public void setTitle(String title) { this.title = title; }
        public List<String> getMembers() { return Collections.unmodifiableList(members); }
    }
}
